// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMS.Data;

#nullable disable

namespace PMS.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311155401_AddTaluks")]
    partial class AddTaluks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PMS.Web.Models.Entities.ActionReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("APCCFDecisionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DecisionAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("OfficerId")
                        .HasColumnType("int");

                    b.Property<int>("PetitionId")
                        .HasColumnType("int");

                    b.Property<string>("ReportText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReportId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("PetitionId");

                    b.ToTable("ActionReports");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.ActionReportAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentId");

                    b.HasIndex("ReportId");

                    b.ToTable("ActionReportAttachments");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.ComplaintCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("ComplaintCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Illegal Felling of Trees"
                        },
                        new
                        {
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Encroachment of Forest Land"
                        },
                        new
                        {
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Poaching / Wildlife Crime"
                        },
                        new
                        {
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Corruption / Bribery"
                        },
                        new
                        {
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Misappropriation of Funds"
                        },
                        new
                        {
                            CategoryId = 6,
                            IsActive = true,
                            Name = "Illegal Mining / Quarrying"
                        },
                        new
                        {
                            CategoryId = 7,
                            IsActive = true,
                            Name = "Forest Fire (Negligence)"
                        },
                        new
                        {
                            CategoryId = 8,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DistrictId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            IsActive = true,
                            Name = "Bengaluru Urban"
                        },
                        new
                        {
                            DistrictId = 2,
                            IsActive = true,
                            Name = "Bengaluru Rural"
                        },
                        new
                        {
                            DistrictId = 3,
                            IsActive = true,
                            Name = "Mysuru"
                        },
                        new
                        {
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Tumakuru"
                        },
                        new
                        {
                            DistrictId = 5,
                            IsActive = true,
                            Name = "Shivamogga"
                        },
                        new
                        {
                            DistrictId = 6,
                            IsActive = true,
                            Name = "Dakshina Kannada"
                        },
                        new
                        {
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Uttara Kannada"
                        },
                        new
                        {
                            DistrictId = 8,
                            IsActive = true,
                            Name = "Kodagu"
                        },
                        new
                        {
                            DistrictId = 9,
                            IsActive = true,
                            Name = "Hassan"
                        },
                        new
                        {
                            DistrictId = 10,
                            IsActive = true,
                            Name = "Chikkamagaluru"
                        },
                        new
                        {
                            DistrictId = 11,
                            IsActive = true,
                            Name = "Mandya"
                        },
                        new
                        {
                            DistrictId = 12,
                            IsActive = true,
                            Name = "Chamarajanagar"
                        },
                        new
                        {
                            DistrictId = 13,
                            IsActive = true,
                            Name = "Ramanagara"
                        },
                        new
                        {
                            DistrictId = 14,
                            IsActive = true,
                            Name = "Kolar"
                        },
                        new
                        {
                            DistrictId = 15,
                            IsActive = true,
                            Name = "Chitradurga"
                        },
                        new
                        {
                            DistrictId = 16,
                            IsActive = true,
                            Name = "Davanagere"
                        },
                        new
                        {
                            DistrictId = 17,
                            IsActive = true,
                            Name = "Haveri"
                        },
                        new
                        {
                            DistrictId = 18,
                            IsActive = true,
                            Name = "Dharwad"
                        },
                        new
                        {
                            DistrictId = 19,
                            IsActive = true,
                            Name = "Gadag"
                        },
                        new
                        {
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Belagavi"
                        },
                        new
                        {
                            DistrictId = 21,
                            IsActive = true,
                            Name = "Vijayapura"
                        },
                        new
                        {
                            DistrictId = 22,
                            IsActive = true,
                            Name = "Bagalkot"
                        },
                        new
                        {
                            DistrictId = 23,
                            IsActive = true,
                            Name = "Ballari"
                        },
                        new
                        {
                            DistrictId = 24,
                            IsActive = true,
                            Name = "Koppal"
                        },
                        new
                        {
                            DistrictId = 25,
                            IsActive = true,
                            Name = "Raichur"
                        },
                        new
                        {
                            DistrictId = 26,
                            IsActive = true,
                            Name = "Yadgir"
                        },
                        new
                        {
                            DistrictId = 27,
                            IsActive = true,
                            Name = "Kalaburagi"
                        },
                        new
                        {
                            DistrictId = 28,
                            IsActive = true,
                            Name = "Bidar"
                        },
                        new
                        {
                            DistrictId = 29,
                            IsActive = true,
                            Name = "Udupi"
                        },
                        new
                        {
                            DistrictId = 30,
                            IsActive = true,
                            Name = "Chikkaballapur"
                        },
                        new
                        {
                            DistrictId = 31,
                            IsActive = true,
                            Name = "Vijayanagara"
                        });
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Petition", b =>
                {
                    b.Property<int>("PetitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetitionId"));

                    b.Property<string>("APCCFRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedOfficeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<int?>("ComplainantDistrictId")
                        .HasColumnType("int");

                    b.Property<string>("ComplainantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplainantPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComplainantTalukId")
                        .HasColumnType("int");

                    b.Property<string>("ComplainantVillage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComplaintCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOfflineEntry")
                        .HasColumnType("bit");

                    b.Property<int>("LocationDistrictId")
                        .HasColumnType("int");

                    b.Property<string>("LocationPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationTalukId")
                        .HasColumnType("int");

                    b.Property<string>("LocationVillage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("OARecommendation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OARemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetitionApplicationId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RecommendedOfficeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RecommendedOfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScrutinizedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ScrutinizedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PetitionId");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("ComplainantDistrictId");

                    b.HasIndex("ComplainantTalukId");

                    b.HasIndex("ComplaintCategoryId");

                    b.HasIndex("LocationDistrictId");

                    b.HasIndex("LocationTalukId");

                    b.HasIndex("PetitionApplicationId")
                        .IsUnique();

                    b.HasIndex("RecommendedOfficerId");

                    b.HasIndex("ScrutinizedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Petitions");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.PetitionAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PetitionId")
                        .HasColumnType("int");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentId");

                    b.HasIndex("PetitionId");

                    b.ToTable("PetitionAttachments");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.PetitionWorkflowLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InternalRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetitionId")
                        .HasColumnType("int");

                    b.Property<string>("PublicLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LogId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("PetitionId");

                    b.ToTable("PetitionWorkflowLogs");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Taluk", b =>
                {
                    b.Property<int>("TalukId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalukId"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TalukId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Taluks");

                    b.HasData(
                        new
                        {
                            TalukId = 1,
                            DistrictId = 1,
                            IsActive = true,
                            Name = "Anekal"
                        },
                        new
                        {
                            TalukId = 2,
                            DistrictId = 1,
                            IsActive = true,
                            Name = "Bengaluru East"
                        },
                        new
                        {
                            TalukId = 3,
                            DistrictId = 1,
                            IsActive = true,
                            Name = "Bengaluru North"
                        },
                        new
                        {
                            TalukId = 4,
                            DistrictId = 1,
                            IsActive = true,
                            Name = "Bengaluru South"
                        },
                        new
                        {
                            TalukId = 5,
                            DistrictId = 1,
                            IsActive = true,
                            Name = "Yeshwanthapura"
                        },
                        new
                        {
                            TalukId = 6,
                            DistrictId = 2,
                            IsActive = true,
                            Name = "Devanahalli"
                        },
                        new
                        {
                            TalukId = 7,
                            DistrictId = 2,
                            IsActive = true,
                            Name = "Doddaballapur"
                        },
                        new
                        {
                            TalukId = 8,
                            DistrictId = 2,
                            IsActive = true,
                            Name = "Hosakote"
                        },
                        new
                        {
                            TalukId = 9,
                            DistrictId = 2,
                            IsActive = true,
                            Name = "Nelamangala"
                        },
                        new
                        {
                            TalukId = 10,
                            DistrictId = 3,
                            IsActive = true,
                            Name = "H.D. Kote"
                        },
                        new
                        {
                            TalukId = 11,
                            DistrictId = 3,
                            IsActive = true,
                            Name = "Hunsur"
                        },
                        new
                        {
                            TalukId = 12,
                            DistrictId = 3,
                            IsActive = true,
                            Name = "K.R. Nagar"
                        },
                        new
                        {
                            TalukId = 13,
                            DistrictId = 3,
                            IsActive = true,
                            Name = "Mysuru"
                        },
                        new
                        {
                            TalukId = 14,
                            DistrictId = 3,
                            IsActive = true,
                            Name = "Nanjangud"
                        },
                        new
                        {
                            TalukId = 15,
                            DistrictId = 3,
                            IsActive = true,
                            Name = "Periyapatna"
                        },
                        new
                        {
                            TalukId = 16,
                            DistrictId = 3,
                            IsActive = true,
                            Name = "T. Narasipura"
                        },
                        new
                        {
                            TalukId = 17,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Chiknayakanhalli"
                        },
                        new
                        {
                            TalukId = 18,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Gubbi"
                        },
                        new
                        {
                            TalukId = 19,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Koratagere"
                        },
                        new
                        {
                            TalukId = 20,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Kunigal"
                        },
                        new
                        {
                            TalukId = 21,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Madhugiri"
                        },
                        new
                        {
                            TalukId = 22,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Pavagada"
                        },
                        new
                        {
                            TalukId = 23,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Sira"
                        },
                        new
                        {
                            TalukId = 24,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Tiptur"
                        },
                        new
                        {
                            TalukId = 25,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Tumakuru"
                        },
                        new
                        {
                            TalukId = 26,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Turuvekere"
                        },
                        new
                        {
                            TalukId = 27,
                            DistrictId = 5,
                            IsActive = true,
                            Name = "Bhadravati"
                        },
                        new
                        {
                            TalukId = 28,
                            DistrictId = 5,
                            IsActive = true,
                            Name = "Hosanagara"
                        },
                        new
                        {
                            TalukId = 29,
                            DistrictId = 5,
                            IsActive = true,
                            Name = "Kelur"
                        },
                        new
                        {
                            TalukId = 30,
                            DistrictId = 5,
                            IsActive = true,
                            Name = "Sagara"
                        },
                        new
                        {
                            TalukId = 31,
                            DistrictId = 5,
                            IsActive = true,
                            Name = "Shikaripur"
                        },
                        new
                        {
                            TalukId = 32,
                            DistrictId = 5,
                            IsActive = true,
                            Name = "Shivamogga"
                        },
                        new
                        {
                            TalukId = 33,
                            DistrictId = 5,
                            IsActive = true,
                            Name = "Sorab"
                        },
                        new
                        {
                            TalukId = 34,
                            DistrictId = 5,
                            IsActive = true,
                            Name = "Thirthahalli"
                        },
                        new
                        {
                            TalukId = 35,
                            DistrictId = 6,
                            IsActive = true,
                            Name = "Bantwal"
                        },
                        new
                        {
                            TalukId = 36,
                            DistrictId = 6,
                            IsActive = true,
                            Name = "Belthangady"
                        },
                        new
                        {
                            TalukId = 37,
                            DistrictId = 6,
                            IsActive = true,
                            Name = "Kadaba"
                        },
                        new
                        {
                            TalukId = 38,
                            DistrictId = 6,
                            IsActive = true,
                            Name = "Mangaluru"
                        },
                        new
                        {
                            TalukId = 39,
                            DistrictId = 6,
                            IsActive = true,
                            Name = "Moodabidri"
                        },
                        new
                        {
                            TalukId = 40,
                            DistrictId = 6,
                            IsActive = true,
                            Name = "Puttur"
                        },
                        new
                        {
                            TalukId = 41,
                            DistrictId = 6,
                            IsActive = true,
                            Name = "Sullia"
                        },
                        new
                        {
                            TalukId = 42,
                            DistrictId = 6,
                            IsActive = true,
                            Name = "Vitla"
                        },
                        new
                        {
                            TalukId = 43,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Ankola"
                        },
                        new
                        {
                            TalukId = 44,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Bhatkal"
                        },
                        new
                        {
                            TalukId = 45,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Dandeli"
                        },
                        new
                        {
                            TalukId = 46,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Haliyal"
                        },
                        new
                        {
                            TalukId = 47,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Honavar"
                        },
                        new
                        {
                            TalukId = 48,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Joida"
                        },
                        new
                        {
                            TalukId = 49,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Karwar"
                        },
                        new
                        {
                            TalukId = 50,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Kumta"
                        },
                        new
                        {
                            TalukId = 51,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Mundgod"
                        },
                        new
                        {
                            TalukId = 52,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Siddapur"
                        },
                        new
                        {
                            TalukId = 53,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Sirsi"
                        },
                        new
                        {
                            TalukId = 54,
                            DistrictId = 7,
                            IsActive = true,
                            Name = "Yellapur"
                        },
                        new
                        {
                            TalukId = 55,
                            DistrictId = 8,
                            IsActive = true,
                            Name = "Madikeri"
                        },
                        new
                        {
                            TalukId = 56,
                            DistrictId = 8,
                            IsActive = true,
                            Name = "Somwarpet"
                        },
                        new
                        {
                            TalukId = 57,
                            DistrictId = 8,
                            IsActive = true,
                            Name = "Virajpet"
                        },
                        new
                        {
                            TalukId = 58,
                            DistrictId = 9,
                            IsActive = true,
                            Name = "Alur"
                        },
                        new
                        {
                            TalukId = 59,
                            DistrictId = 9,
                            IsActive = true,
                            Name = "Arakalagudu"
                        },
                        new
                        {
                            TalukId = 60,
                            DistrictId = 9,
                            IsActive = true,
                            Name = "Arkalgud"
                        },
                        new
                        {
                            TalukId = 61,
                            DistrictId = 9,
                            IsActive = true,
                            Name = "Belur"
                        },
                        new
                        {
                            TalukId = 62,
                            DistrictId = 9,
                            IsActive = true,
                            Name = "Channarayapatna"
                        },
                        new
                        {
                            TalukId = 63,
                            DistrictId = 9,
                            IsActive = true,
                            Name = "Hassan"
                        },
                        new
                        {
                            TalukId = 64,
                            DistrictId = 9,
                            IsActive = true,
                            Name = "Holenarasipur"
                        },
                        new
                        {
                            TalukId = 65,
                            DistrictId = 9,
                            IsActive = true,
                            Name = "Sakaleshapura"
                        },
                        new
                        {
                            TalukId = 66,
                            DistrictId = 10,
                            IsActive = true,
                            Name = "Chikkamagaluru"
                        },
                        new
                        {
                            TalukId = 67,
                            DistrictId = 10,
                            IsActive = true,
                            Name = "Kadur"
                        },
                        new
                        {
                            TalukId = 68,
                            DistrictId = 10,
                            IsActive = true,
                            Name = "Koppa"
                        },
                        new
                        {
                            TalukId = 69,
                            DistrictId = 10,
                            IsActive = true,
                            Name = "Mudigere"
                        },
                        new
                        {
                            TalukId = 70,
                            DistrictId = 10,
                            IsActive = true,
                            Name = "N.R. Pura"
                        },
                        new
                        {
                            TalukId = 71,
                            DistrictId = 10,
                            IsActive = true,
                            Name = "Sringeri"
                        },
                        new
                        {
                            TalukId = 72,
                            DistrictId = 10,
                            IsActive = true,
                            Name = "Tarikere"
                        },
                        new
                        {
                            TalukId = 73,
                            DistrictId = 11,
                            IsActive = true,
                            Name = "Kirugavalu"
                        },
                        new
                        {
                            TalukId = 74,
                            DistrictId = 11,
                            IsActive = true,
                            Name = "Krishnarajapete"
                        },
                        new
                        {
                            TalukId = 75,
                            DistrictId = 11,
                            IsActive = true,
                            Name = "Maddur"
                        },
                        new
                        {
                            TalukId = 76,
                            DistrictId = 11,
                            IsActive = true,
                            Name = "Malavalli"
                        },
                        new
                        {
                            TalukId = 77,
                            DistrictId = 11,
                            IsActive = true,
                            Name = "Mandya"
                        },
                        new
                        {
                            TalukId = 78,
                            DistrictId = 11,
                            IsActive = true,
                            Name = "Nagamangala"
                        },
                        new
                        {
                            TalukId = 79,
                            DistrictId = 11,
                            IsActive = true,
                            Name = "Pandavapura"
                        },
                        new
                        {
                            TalukId = 80,
                            DistrictId = 11,
                            IsActive = true,
                            Name = "Shrirangapattana"
                        },
                        new
                        {
                            TalukId = 81,
                            DistrictId = 12,
                            IsActive = true,
                            Name = "Chamarajanagar"
                        },
                        new
                        {
                            TalukId = 82,
                            DistrictId = 12,
                            IsActive = true,
                            Name = "Gundlupet"
                        },
                        new
                        {
                            TalukId = 83,
                            DistrictId = 12,
                            IsActive = true,
                            Name = "Kollegal"
                        },
                        new
                        {
                            TalukId = 84,
                            DistrictId = 12,
                            IsActive = true,
                            Name = "Yelandur"
                        },
                        new
                        {
                            TalukId = 85,
                            DistrictId = 13,
                            IsActive = true,
                            Name = "Channapatna"
                        },
                        new
                        {
                            TalukId = 86,
                            DistrictId = 13,
                            IsActive = true,
                            Name = "Kanakapura"
                        },
                        new
                        {
                            TalukId = 87,
                            DistrictId = 13,
                            IsActive = true,
                            Name = "Magadi"
                        },
                        new
                        {
                            TalukId = 88,
                            DistrictId = 13,
                            IsActive = true,
                            Name = "Ramanagara"
                        },
                        new
                        {
                            TalukId = 89,
                            DistrictId = 14,
                            IsActive = true,
                            Name = "Bangarpet"
                        },
                        new
                        {
                            TalukId = 90,
                            DistrictId = 14,
                            IsActive = true,
                            Name = "K.G.F"
                        },
                        new
                        {
                            TalukId = 91,
                            DistrictId = 14,
                            IsActive = true,
                            Name = "Kolar"
                        },
                        new
                        {
                            TalukId = 92,
                            DistrictId = 14,
                            IsActive = true,
                            Name = "Malur"
                        },
                        new
                        {
                            TalukId = 93,
                            DistrictId = 14,
                            IsActive = true,
                            Name = "Mulbagal"
                        },
                        new
                        {
                            TalukId = 94,
                            DistrictId = 14,
                            IsActive = true,
                            Name = "Srinivaspur"
                        },
                        new
                        {
                            TalukId = 95,
                            DistrictId = 15,
                            IsActive = true,
                            Name = "Challakere"
                        },
                        new
                        {
                            TalukId = 96,
                            DistrictId = 15,
                            IsActive = true,
                            Name = "Chitradurga"
                        },
                        new
                        {
                            TalukId = 97,
                            DistrictId = 15,
                            IsActive = true,
                            Name = "Hiriyur"
                        },
                        new
                        {
                            TalukId = 98,
                            DistrictId = 15,
                            IsActive = true,
                            Name = "Holalkere"
                        },
                        new
                        {
                            TalukId = 99,
                            DistrictId = 15,
                            IsActive = true,
                            Name = "Hosadurga"
                        },
                        new
                        {
                            TalukId = 100,
                            DistrictId = 15,
                            IsActive = true,
                            Name = "Molakalmuru"
                        },
                        new
                        {
                            TalukId = 101,
                            DistrictId = 16,
                            IsActive = true,
                            Name = "Channagiri"
                        },
                        new
                        {
                            TalukId = 102,
                            DistrictId = 16,
                            IsActive = true,
                            Name = "Davanagere"
                        },
                        new
                        {
                            TalukId = 103,
                            DistrictId = 16,
                            IsActive = true,
                            Name = "Harihara"
                        },
                        new
                        {
                            TalukId = 104,
                            DistrictId = 16,
                            IsActive = true,
                            Name = "Honnali"
                        },
                        new
                        {
                            TalukId = 105,
                            DistrictId = 16,
                            IsActive = true,
                            Name = "Jagalur"
                        },
                        new
                        {
                            TalukId = 106,
                            DistrictId = 16,
                            IsActive = true,
                            Name = "Nyamathi"
                        },
                        new
                        {
                            TalukId = 107,
                            DistrictId = 17,
                            IsActive = true,
                            Name = "Byadagi"
                        },
                        new
                        {
                            TalukId = 108,
                            DistrictId = 17,
                            IsActive = true,
                            Name = "Hanagal"
                        },
                        new
                        {
                            TalukId = 109,
                            DistrictId = 17,
                            IsActive = true,
                            Name = "Haveri"
                        },
                        new
                        {
                            TalukId = 110,
                            DistrictId = 17,
                            IsActive = true,
                            Name = "Hirekerur"
                        },
                        new
                        {
                            TalukId = 111,
                            DistrictId = 17,
                            IsActive = true,
                            Name = "Ranibennur"
                        },
                        new
                        {
                            TalukId = 112,
                            DistrictId = 17,
                            IsActive = true,
                            Name = "Savanur"
                        },
                        new
                        {
                            TalukId = 113,
                            DistrictId = 17,
                            IsActive = true,
                            Name = "Shiggaon"
                        },
                        new
                        {
                            TalukId = 114,
                            DistrictId = 18,
                            IsActive = true,
                            Name = "Dharwad"
                        },
                        new
                        {
                            TalukId = 115,
                            DistrictId = 18,
                            IsActive = true,
                            Name = "Hubli"
                        },
                        new
                        {
                            TalukId = 116,
                            DistrictId = 18,
                            IsActive = true,
                            Name = "Kalghatgi"
                        },
                        new
                        {
                            TalukId = 117,
                            DistrictId = 18,
                            IsActive = true,
                            Name = "Kundgol"
                        },
                        new
                        {
                            TalukId = 118,
                            DistrictId = 18,
                            IsActive = true,
                            Name = "Navalgund"
                        },
                        new
                        {
                            TalukId = 119,
                            DistrictId = 19,
                            IsActive = true,
                            Name = "Gadag"
                        },
                        new
                        {
                            TalukId = 120,
                            DistrictId = 19,
                            IsActive = true,
                            Name = "Mundargi"
                        },
                        new
                        {
                            TalukId = 121,
                            DistrictId = 19,
                            IsActive = true,
                            Name = "Nargund"
                        },
                        new
                        {
                            TalukId = 122,
                            DistrictId = 19,
                            IsActive = true,
                            Name = "Ron"
                        },
                        new
                        {
                            TalukId = 123,
                            DistrictId = 19,
                            IsActive = true,
                            Name = "Shirahatti"
                        },
                        new
                        {
                            TalukId = 124,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Athani"
                        },
                        new
                        {
                            TalukId = 125,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Bailhongal"
                        },
                        new
                        {
                            TalukId = 126,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Belagavi"
                        },
                        new
                        {
                            TalukId = 127,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Chikodi"
                        },
                        new
                        {
                            TalukId = 128,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Gokak"
                        },
                        new
                        {
                            TalukId = 129,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Hukkeri"
                        },
                        new
                        {
                            TalukId = 130,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Kagwad"
                        },
                        new
                        {
                            TalukId = 131,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Khanapur"
                        },
                        new
                        {
                            TalukId = 132,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Mudalgi"
                        },
                        new
                        {
                            TalukId = 133,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Ramdurg"
                        },
                        new
                        {
                            TalukId = 134,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Raybag"
                        },
                        new
                        {
                            TalukId = 135,
                            DistrictId = 20,
                            IsActive = true,
                            Name = "Savadatti"
                        },
                        new
                        {
                            TalukId = 136,
                            DistrictId = 21,
                            IsActive = true,
                            Name = "Basavana Bagewadi"
                        },
                        new
                        {
                            TalukId = 137,
                            DistrictId = 21,
                            IsActive = true,
                            Name = "Devar Hippargi"
                        },
                        new
                        {
                            TalukId = 138,
                            DistrictId = 21,
                            IsActive = true,
                            Name = "Indi"
                        },
                        new
                        {
                            TalukId = 139,
                            DistrictId = 21,
                            IsActive = true,
                            Name = "Muddebihal"
                        },
                        new
                        {
                            TalukId = 140,
                            DistrictId = 21,
                            IsActive = true,
                            Name = "Sindagi"
                        },
                        new
                        {
                            TalukId = 141,
                            DistrictId = 21,
                            IsActive = true,
                            Name = "Vijayapura"
                        },
                        new
                        {
                            TalukId = 142,
                            DistrictId = 22,
                            IsActive = true,
                            Name = "Bagalkot"
                        },
                        new
                        {
                            TalukId = 143,
                            DistrictId = 22,
                            IsActive = true,
                            Name = "Badami"
                        },
                        new
                        {
                            TalukId = 144,
                            DistrictId = 22,
                            IsActive = true,
                            Name = "Bilgi"
                        },
                        new
                        {
                            TalukId = 145,
                            DistrictId = 22,
                            IsActive = true,
                            Name = "Hunagund"
                        },
                        new
                        {
                            TalukId = 146,
                            DistrictId = 22,
                            IsActive = true,
                            Name = "Jamkhandi"
                        },
                        new
                        {
                            TalukId = 147,
                            DistrictId = 22,
                            IsActive = true,
                            Name = "Mudhol"
                        },
                        new
                        {
                            TalukId = 148,
                            DistrictId = 23,
                            IsActive = true,
                            Name = "Ballari"
                        },
                        new
                        {
                            TalukId = 149,
                            DistrictId = 23,
                            IsActive = true,
                            Name = "Hadagalli"
                        },
                        new
                        {
                            TalukId = 150,
                            DistrictId = 23,
                            IsActive = true,
                            Name = "Hagaribommanahalli"
                        },
                        new
                        {
                            TalukId = 151,
                            DistrictId = 23,
                            IsActive = true,
                            Name = "Hospet"
                        },
                        new
                        {
                            TalukId = 152,
                            DistrictId = 23,
                            IsActive = true,
                            Name = "Kudligi"
                        },
                        new
                        {
                            TalukId = 153,
                            DistrictId = 23,
                            IsActive = true,
                            Name = "Sandur"
                        },
                        new
                        {
                            TalukId = 154,
                            DistrictId = 23,
                            IsActive = true,
                            Name = "Siruguppa"
                        },
                        new
                        {
                            TalukId = 155,
                            DistrictId = 24,
                            IsActive = true,
                            Name = "Gangavathi"
                        },
                        new
                        {
                            TalukId = 156,
                            DistrictId = 24,
                            IsActive = true,
                            Name = "Koppal"
                        },
                        new
                        {
                            TalukId = 157,
                            DistrictId = 24,
                            IsActive = true,
                            Name = "Kustagi"
                        },
                        new
                        {
                            TalukId = 158,
                            DistrictId = 24,
                            IsActive = true,
                            Name = "Yelburga"
                        },
                        new
                        {
                            TalukId = 159,
                            DistrictId = 25,
                            IsActive = true,
                            Name = "Devadurga"
                        },
                        new
                        {
                            TalukId = 160,
                            DistrictId = 25,
                            IsActive = true,
                            Name = "Lingsugur"
                        },
                        new
                        {
                            TalukId = 161,
                            DistrictId = 25,
                            IsActive = true,
                            Name = "Manvi"
                        },
                        new
                        {
                            TalukId = 162,
                            DistrictId = 25,
                            IsActive = true,
                            Name = "Raichur"
                        },
                        new
                        {
                            TalukId = 163,
                            DistrictId = 25,
                            IsActive = true,
                            Name = "Sindhanur"
                        },
                        new
                        {
                            TalukId = 164,
                            DistrictId = 26,
                            IsActive = true,
                            Name = "Gurmitkal"
                        },
                        new
                        {
                            TalukId = 165,
                            DistrictId = 26,
                            IsActive = true,
                            Name = "Hunsagi"
                        },
                        new
                        {
                            TalukId = 166,
                            DistrictId = 26,
                            IsActive = true,
                            Name = "Shahapur"
                        },
                        new
                        {
                            TalukId = 167,
                            DistrictId = 26,
                            IsActive = true,
                            Name = "Shorapur"
                        },
                        new
                        {
                            TalukId = 168,
                            DistrictId = 26,
                            IsActive = true,
                            Name = "Yadgir"
                        },
                        new
                        {
                            TalukId = 169,
                            DistrictId = 27,
                            IsActive = true,
                            Name = "Aland"
                        },
                        new
                        {
                            TalukId = 170,
                            DistrictId = 27,
                            IsActive = true,
                            Name = "Afzalpur"
                        },
                        new
                        {
                            TalukId = 171,
                            DistrictId = 27,
                            IsActive = true,
                            Name = "Chincholi"
                        },
                        new
                        {
                            TalukId = 172,
                            DistrictId = 27,
                            IsActive = true,
                            Name = "Chittapur"
                        },
                        new
                        {
                            TalukId = 173,
                            DistrictId = 27,
                            IsActive = true,
                            Name = "Jevargi"
                        },
                        new
                        {
                            TalukId = 174,
                            DistrictId = 27,
                            IsActive = true,
                            Name = "Kalaburagi"
                        },
                        new
                        {
                            TalukId = 175,
                            DistrictId = 27,
                            IsActive = true,
                            Name = "Sedam"
                        },
                        new
                        {
                            TalukId = 176,
                            DistrictId = 27,
                            IsActive = true,
                            Name = "Shahaabad"
                        },
                        new
                        {
                            TalukId = 177,
                            DistrictId = 27,
                            IsActive = true,
                            Name = "Wadi"
                        },
                        new
                        {
                            TalukId = 178,
                            DistrictId = 28,
                            IsActive = true,
                            Name = "Aurad"
                        },
                        new
                        {
                            TalukId = 179,
                            DistrictId = 28,
                            IsActive = true,
                            Name = "Basavakalyan"
                        },
                        new
                        {
                            TalukId = 180,
                            DistrictId = 28,
                            IsActive = true,
                            Name = "Bhalki"
                        },
                        new
                        {
                            TalukId = 181,
                            DistrictId = 28,
                            IsActive = true,
                            Name = "Bidar"
                        },
                        new
                        {
                            TalukId = 182,
                            DistrictId = 28,
                            IsActive = true,
                            Name = "Humnabad"
                        },
                        new
                        {
                            TalukId = 183,
                            DistrictId = 29,
                            IsActive = true,
                            Name = "Karkala"
                        },
                        new
                        {
                            TalukId = 184,
                            DistrictId = 29,
                            IsActive = true,
                            Name = "Kundapur"
                        },
                        new
                        {
                            TalukId = 185,
                            DistrictId = 29,
                            IsActive = true,
                            Name = "Udupi"
                        },
                        new
                        {
                            TalukId = 186,
                            DistrictId = 30,
                            IsActive = true,
                            Name = "Bagepalli"
                        },
                        new
                        {
                            TalukId = 187,
                            DistrictId = 30,
                            IsActive = true,
                            Name = "Chikkaballapur"
                        },
                        new
                        {
                            TalukId = 188,
                            DistrictId = 30,
                            IsActive = true,
                            Name = "Chintamani"
                        },
                        new
                        {
                            TalukId = 189,
                            DistrictId = 30,
                            IsActive = true,
                            Name = "Gauribidanur"
                        },
                        new
                        {
                            TalukId = 190,
                            DistrictId = 30,
                            IsActive = true,
                            Name = "Gudibanda"
                        },
                        new
                        {
                            TalukId = 191,
                            DistrictId = 30,
                            IsActive = true,
                            Name = "Sidlaghatta"
                        },
                        new
                        {
                            TalukId = 192,
                            DistrictId = 31,
                            IsActive = true,
                            Name = "Hagaribommanahalli"
                        },
                        new
                        {
                            TalukId = 193,
                            DistrictId = 31,
                            IsActive = true,
                            Name = "Hoovina Hadagali"
                        },
                        new
                        {
                            TalukId = 194,
                            DistrictId = 31,
                            IsActive = true,
                            Name = "Hosapete"
                        },
                        new
                        {
                            TalukId = 195,
                            DistrictId = 31,
                            IsActive = true,
                            Name = "Kottur"
                        },
                        new
                        {
                            TalukId = 196,
                            DistrictId = 31,
                            IsActive = true,
                            Name = "Kudligi"
                        },
                        new
                        {
                            TalukId = 197,
                            DistrictId = 31,
                            IsActive = true,
                            Name = "Sandur"
                        },
                        new
                        {
                            TalukId = 198,
                            DistrictId = 31,
                            IsActive = true,
                            Name = "Siruguppa"
                        });
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OfficeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TalukId")
                        .HasColumnType("int");

                    b.Property<string>("Village")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.HasIndex("TalukId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MobileNumber = "9000000001",
                            Name = "APCCF Vigilance",
                            Role = "APCCF"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MobileNumber = "9000000002",
                            Name = "Office Assistant",
                            Role = "OfficeAssistant"
                        });
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.ActionReport", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.User", "Officer")
                        .WithMany("ActionReports")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMS.Web.Models.Entities.Petition", "Petition")
                        .WithMany("ActionReports")
                        .HasForeignKey("PetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Officer");

                    b.Navigation("Petition");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.ActionReportAttachment", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.ActionReport", "Report")
                        .WithMany("Attachments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Petition", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.User", "AssignedOfficer")
                        .WithMany("AssignedPetitions")
                        .HasForeignKey("AssignedOfficerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.District", "ComplainantDistrict")
                        .WithMany()
                        .HasForeignKey("ComplainantDistrictId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.Taluk", "ComplainantTaluk")
                        .WithMany()
                        .HasForeignKey("ComplainantTalukId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.ComplaintCategory", "ComplaintCategory")
                        .WithMany()
                        .HasForeignKey("ComplaintCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMS.Web.Models.Entities.District", "LocationDistrict")
                        .WithMany()
                        .HasForeignKey("LocationDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMS.Web.Models.Entities.Taluk", "LocationTaluk")
                        .WithMany()
                        .HasForeignKey("LocationTalukId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.User", "RecommendedOfficer")
                        .WithMany()
                        .HasForeignKey("RecommendedOfficerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.User", "ScrutinizedBy")
                        .WithMany()
                        .HasForeignKey("ScrutinizedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.User", null)
                        .WithMany("SubmittedPetitions")
                        .HasForeignKey("UserId");

                    b.Navigation("AssignedOfficer");

                    b.Navigation("ComplainantDistrict");

                    b.Navigation("ComplainantTaluk");

                    b.Navigation("ComplaintCategory");

                    b.Navigation("LocationDistrict");

                    b.Navigation("LocationTaluk");

                    b.Navigation("RecommendedOfficer");

                    b.Navigation("ScrutinizedBy");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.PetitionAttachment", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.Petition", "Petition")
                        .WithMany("Attachments")
                        .HasForeignKey("PetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Petition");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.PetitionWorkflowLog", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.User", "ActorUser")
                        .WithMany("WorkflowLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.Petition", "Petition")
                        .WithMany("WorkflowLogs")
                        .HasForeignKey("PetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Petition");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Taluk", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.District", "District")
                        .WithMany("Taluks")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.User", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("PMS.Web.Models.Entities.Taluk", "Taluk")
                        .WithMany()
                        .HasForeignKey("TalukId");

                    b.Navigation("District");

                    b.Navigation("Taluk");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.ActionReport", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.District", b =>
                {
                    b.Navigation("Taluks");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Petition", b =>
                {
                    b.Navigation("ActionReports");

                    b.Navigation("Attachments");

                    b.Navigation("WorkflowLogs");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.User", b =>
                {
                    b.Navigation("ActionReports");

                    b.Navigation("AssignedPetitions");

                    b.Navigation("SubmittedPetitions");

                    b.Navigation("WorkflowLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
