// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMS.Data;

#nullable disable

namespace PMS.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PMS.Web.Models.Entities.ActionReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("APCCFDecisionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DecisionAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("OfficerId")
                        .HasColumnType("int");

                    b.Property<int>("PetitionId")
                        .HasColumnType("int");

                    b.Property<string>("ReportText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReportId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("PetitionId");

                    b.ToTable("ActionReports");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.ActionReportAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentId");

                    b.HasIndex("ReportId");

                    b.ToTable("ActionReportAttachments");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.ComplaintCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("ComplaintCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Illegal Felling of Trees"
                        },
                        new
                        {
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Encroachment of Forest Land"
                        },
                        new
                        {
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Poaching / Wildlife Crime"
                        },
                        new
                        {
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Corruption / Bribery"
                        },
                        new
                        {
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Misappropriation of Funds"
                        },
                        new
                        {
                            CategoryId = 6,
                            IsActive = true,
                            Name = "Illegal Mining / Quarrying"
                        },
                        new
                        {
                            CategoryId = 7,
                            IsActive = true,
                            Name = "Forest Fire (Negligence)"
                        },
                        new
                        {
                            CategoryId = 8,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KGISCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameKN")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DistrictId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Hobli", b =>
                {
                    b.Property<int>("HobliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HobliId"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("MasterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameKN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TalukId")
                        .HasColumnType("int");

                    b.HasKey("HobliId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("TalukId");

                    b.ToTable("Hoblis");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Petition", b =>
                {
                    b.Property<int>("PetitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetitionId"));

                    b.Property<string>("APCCFDocumentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("APCCFRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedOAId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedOfficeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedToOAAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ComplainantDistrictId")
                        .HasColumnType("int");

                    b.Property<int?>("ComplainantHobliId")
                        .HasColumnType("int");

                    b.Property<bool?>("ComplainantIsUrban")
                        .HasColumnType("bit");

                    b.Property<string>("ComplainantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplainantPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComplainantTalukId")
                        .HasColumnType("int");

                    b.Property<int?>("ComplainantTownId")
                        .HasColumnType("int");

                    b.Property<string>("ComplainantVillage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComplainantVillageId")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOfflineEntry")
                        .HasColumnType("bit");

                    b.Property<int>("LocationDistrictId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationHobliId")
                        .HasColumnType("int");

                    b.Property<bool?>("LocationIsUrban")
                        .HasColumnType("bit");

                    b.Property<string>("LocationPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationTalukId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationTownId")
                        .HasColumnType("int");

                    b.Property<string>("LocationVillage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationVillageId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("OADropReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OADroppedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OARecommendation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OARemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetitionApplicationId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RecommendedOfficeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RecommendedOfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScrutinizedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ScrutinizedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SummaryByOAId")
                        .HasColumnType("int");

                    b.Property<string>("SummaryRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SummarySubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.Property<int?>("UserId2")
                        .HasColumnType("int");

                    b.HasKey("PetitionId");

                    b.HasIndex("AssignedManagerId");

                    b.HasIndex("AssignedOAId");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("ComplainantDistrictId");

                    b.HasIndex("ComplainantHobliId");

                    b.HasIndex("ComplainantTalukId");

                    b.HasIndex("ComplainantTownId");

                    b.HasIndex("ComplainantVillageId");

                    b.HasIndex("ComplaintCategoryId");

                    b.HasIndex("LocationDistrictId");

                    b.HasIndex("LocationHobliId");

                    b.HasIndex("LocationTalukId");

                    b.HasIndex("LocationTownId");

                    b.HasIndex("LocationVillageId");

                    b.HasIndex("PetitionApplicationId")
                        .IsUnique();

                    b.HasIndex("RecommendedOfficerId");

                    b.HasIndex("ScrutinizedByUserId");

                    b.HasIndex("SummaryByOAId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId2");

                    b.ToTable("Petitions");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.PetitionAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PetitionId")
                        .HasColumnType("int");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentId");

                    b.HasIndex("PetitionId");

                    b.ToTable("PetitionAttachments");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.PetitionWorkflowLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InternalRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetitionId")
                        .HasColumnType("int");

                    b.Property<string>("PublicLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LogId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("PetitionId");

                    b.ToTable("PetitionWorkflowLogs");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Taluk", b =>
                {
                    b.Property<int>("TalukId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalukId"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MasterCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameKN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TalukId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Taluks");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Town", b =>
                {
                    b.Property<int>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TownId"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("KGISCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KGISTownId")
                        .HasColumnType("int");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TownType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TownId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OfficeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TalukId")
                        .HasColumnType("int");

                    b.Property<string>("Village")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.HasIndex("TalukId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Village", b =>
                {
                    b.Property<int>("VillageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VillageId"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("HobliId")
                        .HasColumnType("int");

                    b.Property<string>("MasterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameKN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TalukId")
                        .HasColumnType("int");

                    b.HasKey("VillageId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("HobliId");

                    b.HasIndex("TalukId");

                    b.ToTable("Villages");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.ActionReport", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.User", "Officer")
                        .WithMany("ActionReports")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMS.Web.Models.Entities.Petition", "Petition")
                        .WithMany("ActionReports")
                        .HasForeignKey("PetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Officer");

                    b.Navigation("Petition");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.ActionReportAttachment", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.ActionReport", "Report")
                        .WithMany("Attachments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Hobli", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PMS.Web.Models.Entities.Taluk", "Taluk")
                        .WithMany("Hoblis")
                        .HasForeignKey("TalukId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Taluk");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Petition", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.User", "AssignedManager")
                        .WithMany()
                        .HasForeignKey("AssignedManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.User", "AssignedOA")
                        .WithMany()
                        .HasForeignKey("AssignedOAId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.User", "AssignedOfficer")
                        .WithMany()
                        .HasForeignKey("AssignedOfficerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.District", "ComplainantDistrict")
                        .WithMany()
                        .HasForeignKey("ComplainantDistrictId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.Hobli", "ComplainantHobli")
                        .WithMany()
                        .HasForeignKey("ComplainantHobliId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.Taluk", "ComplainantTaluk")
                        .WithMany()
                        .HasForeignKey("ComplainantTalukId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.Town", "ComplainantTown")
                        .WithMany()
                        .HasForeignKey("ComplainantTownId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.Village", "ComplainantVillageNav")
                        .WithMany()
                        .HasForeignKey("ComplainantVillageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.ComplaintCategory", "ComplaintCategory")
                        .WithMany()
                        .HasForeignKey("ComplaintCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMS.Web.Models.Entities.District", "LocationDistrict")
                        .WithMany()
                        .HasForeignKey("LocationDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMS.Web.Models.Entities.Hobli", "LocationHobli")
                        .WithMany()
                        .HasForeignKey("LocationHobliId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.Taluk", "LocationTaluk")
                        .WithMany()
                        .HasForeignKey("LocationTalukId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.Town", "LocationTown")
                        .WithMany()
                        .HasForeignKey("LocationTownId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.Village", "LocationVillageNav")
                        .WithMany()
                        .HasForeignKey("LocationVillageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.User", "RecommendedOfficer")
                        .WithMany()
                        .HasForeignKey("RecommendedOfficerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.User", "ScrutinizedBy")
                        .WithMany()
                        .HasForeignKey("ScrutinizedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.User", "SummaryByOA")
                        .WithMany()
                        .HasForeignKey("SummaryByOAId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.User", "SubmittingUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.User", null)
                        .WithMany("AssignedPetitions")
                        .HasForeignKey("UserId1");

                    b.HasOne("PMS.Web.Models.Entities.User", null)
                        .WithMany("SubmittedPetitions")
                        .HasForeignKey("UserId2");

                    b.Navigation("AssignedManager");

                    b.Navigation("AssignedOA");

                    b.Navigation("AssignedOfficer");

                    b.Navigation("ComplainantDistrict");

                    b.Navigation("ComplainantHobli");

                    b.Navigation("ComplainantTaluk");

                    b.Navigation("ComplainantTown");

                    b.Navigation("ComplainantVillageNav");

                    b.Navigation("ComplaintCategory");

                    b.Navigation("LocationDistrict");

                    b.Navigation("LocationHobli");

                    b.Navigation("LocationTaluk");

                    b.Navigation("LocationTown");

                    b.Navigation("LocationVillageNav");

                    b.Navigation("RecommendedOfficer");

                    b.Navigation("ScrutinizedBy");

                    b.Navigation("SubmittingUser");

                    b.Navigation("SummaryByOA");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.PetitionAttachment", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.Petition", "Petition")
                        .WithMany("Attachments")
                        .HasForeignKey("PetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Petition");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.PetitionWorkflowLog", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.User", "ActorUser")
                        .WithMany("WorkflowLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PMS.Web.Models.Entities.Petition", "Petition")
                        .WithMany("WorkflowLogs")
                        .HasForeignKey("PetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Petition");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Taluk", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.District", "District")
                        .WithMany("Taluks")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Town", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.District", "District")
                        .WithMany("Towns")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.User", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("PMS.Web.Models.Entities.Taluk", "Taluk")
                        .WithMany()
                        .HasForeignKey("TalukId");

                    b.Navigation("District");

                    b.Navigation("Taluk");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Village", b =>
                {
                    b.HasOne("PMS.Web.Models.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PMS.Web.Models.Entities.Hobli", "Hobli")
                        .WithMany("Villages")
                        .HasForeignKey("HobliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMS.Web.Models.Entities.Taluk", "Taluk")
                        .WithMany()
                        .HasForeignKey("TalukId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Hobli");

                    b.Navigation("Taluk");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.ActionReport", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.District", b =>
                {
                    b.Navigation("Taluks");

                    b.Navigation("Towns");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Hobli", b =>
                {
                    b.Navigation("Villages");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Petition", b =>
                {
                    b.Navigation("ActionReports");

                    b.Navigation("Attachments");

                    b.Navigation("WorkflowLogs");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.Taluk", b =>
                {
                    b.Navigation("Hoblis");
                });

            modelBuilder.Entity("PMS.Web.Models.Entities.User", b =>
                {
                    b.Navigation("ActionReports");

                    b.Navigation("AssignedPetitions");

                    b.Navigation("SubmittedPetitions");

                    b.Navigation("WorkflowLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
